export const themeSugestion = [
  'Fantasia Leve',
  'Fantasia Epica',
  'Fantasia Sombria',
  'Medieval Classico',
  'Estilo Senhor dos Aneis',
  'Low Fantasy',
  'High Fantasy',
  'Grimdark',
  'Heroica e Aventura',
  'Intriga Politica',
  'Exploracao e Aventura',
  'Mitologia Nordica',
  'Mitologia Grega',
  'Piratas e Mar',
  'Steampunk',
  'Cyberpunk Fantasy',
  'Pos-Apocaliptico',
  'Western Fantastico',
  'Horror e Terror',
  'Anime e Manga',
  'Magia Selvagem',
  'Dragoes e Bestas',
  'Elfos, Anoes e Magos',
  'Reinos em Guerra',
  'Viagem no Tempo',
] as const;
